spring:
  application:
    name: A-StockPro
  timezone: Asia/Shanghai
  datasource:
    url: jdbc:mysql://localhost:3306/a-stock-pro
    username: root
    password: xxt123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml  # 如果需要自定义SQL文件
  type-aliases-package: com.coriger.model.entity
  global-config:
    db-config:
      id-type: auto

server:
  port: 8090